const quotes = [
              "Your kindness is a strength that lights up every room you enter ✨💫",
              "A heart like yours heals more than words ever could 💖🤲",
              "You don’t just live life—you dance through it with grace 💃🌸",
              "Your wisdom makes the world softer, calmer, and braver 🌿🕊️",
              "You inspire by simply being yourself 🌟🙌",
              "Every step you take shows courage beyond measure 🚶🔥",
              "You see hope where others see doubt 🌈🌻",
              "The way you rise makes others believe they can too ⛰️🌞",
              "Your soul shines brighter than any spotlight ✨🌌",
              "The strength in your silence is louder than noise 🤍🔔",
              "You remind the world that gentleness is power 🕊️💪",
              "In every storm, you are the calm 🌧️☀️",
              "Your presence itself is motivation 🌟💫",
              "You don’t just dream—you make others believe in theirs 🌙🚀",
              "The world is brighter because you refuse to dim 🌞✨",
              "Being around you feels like sunshine on a calm morning ☀️🌼",
              "Every step you dance is a story untold 👣📖",
              "You turn ordinary moments into memories worth keeping 📖💛",
              "Your smile speaks louder than a thousand motivational speeches 😊🌸",
              "Happiness follows wherever your heart goes 🌈💖",
              "You are proof that joy can be contagious 😍✨",
              "Even silence with you feels peaceful 🌿🤍",
              "A dancer of rhythm, a writer of emotions, a healer of hearts—that’s who you are 💃🖋️💚",
              "Your laughter is therapy in itself 😂💫",
              "You paint the world in colors of kindness 🎨🌹",
              "Time spent with you is always time well-lived 🕰️🌷",
              "With you, even simple days feel like celebrations 🎉💃",
              "Peace flows from within you, and everyone around feels it 🌊🕊️",
              "our mind heals, your words inspire, your presence strengthens 🧠💚",
              "You’re living proof that balance between heart and mind creates harmony ⚖️💖",
              "Wellness is in the way you think, act, and love 🌱✨",
              "Your kindness is medicine for tired souls 💊💞",
              "Your words are like therapy—gentle yet powerful 📖🤲",
              "You remind others to breathe, to pause, to heal 🌬️🌸",
              "Around you, stress dissolves into calm 🌿🍃",
              "You are the bridge between chaos and peace 🌉🕊️",
              "Your compassion is the healthiest energy to be around 💚",
              "You dance like poetry, write like truth, and heal like hope 💃✍️🌈",
              "Your art moves the soul, your words move the mind, your kindness moves the heart 🎭📝💖",
              "Your pen has the power to rewrite pain into strength ✍️🔥",
              "Your movements are music made visible 🎶💃",
              "Through words, you build bridges between broken thoughts 🌉📖",
              "A true artist heals not just themselves but the world 🌍🎨",
              "You understand hearts better than most understand words 💞🧠",
              "Your writing whispers truths people are afraid to say ✍️🌌",
              "You listen like a psychologist, create like a writer, and express like a dancer 🎧🖋️💃",
              "Every dance of yours is a heartbeat in motion 💃❤️",
              "Your creativity is therapy in disguise 🎨🧘‍♂️",
              "You carry art, wisdom, and kindness in every form of your being 🌟📖💃",
              "You don’t just hear people—you feel them 👂💖"
            ]